### ISSUE TITLE
app crashed when using this library in conjuction with uk.co.chrisjenx:calligraphy

### ISSUE THREAD

**Issue by markchristopherng** [afollestad/material-dialogs#475]
I already use the calligraphy library to set custom fonts in my project as follows;
`compile 'uk.co.chrisjenx:calligraphy:2.0.2@aar'`

however when i add your library project to my build.gradle as follows
`compile 'com.afollestad:material-dialogs:0.7.2.7@aar'`

the app will work on android 5.0.1 however the app will crash on android 4.4.4

The interesting thing is that i only include your dependecy i have not created any dialogs in the code or referenced any of your classes so unsure why this fails unless you are doing some static intialization in your classes.

The error is as follows

```Groovy
04-24 15:22:37.603: E/AndroidRuntime(18726): FATAL EXCEPTION: main
04-24 15:22:37.603: E/AndroidRuntime(18726): Process: au.com.nab.mobile.android.nabconnect, PID: 18726
04-24 15:22:37.603: E/AndroidRuntime(18726): java.lang.RuntimeException: Unable to start activity ComponentInfo{au.com.nab.mobile.android.nabconnect/au.com.nab.mobile.android.nabconnect.activity.initialize.SplashScreenActivity}: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.os.Looper.loop(Looper.java:136)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread.main(ActivityThread.java:5097)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at dalvik.system.NativeStart.main(Native Method)
04-24 15:22:37.603: E/AndroidRuntime(18726): Caused by: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.view.LayoutInflater.setFactory(LayoutInflater.java:278)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory(CalligraphyLayoutInflater.java:85)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setUpLayoutFactories(CalligraphyLayoutInflater.java:77)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>(CalligraphyLayoutInflater.java:44)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.cloneInContext(CalligraphyLayoutInflater.java:49)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.support.v7.internal.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:69)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.view.LayoutInflater.from(LayoutInflater.java:211)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:296)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at au.com.nab.mobile.android.nabconnect.activity.initialize.SplashScreenActivity.onCreate(SplashScreenActivity.java:46)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.Activity.performCreate(Activity.java:5248)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
04-24 15:22:37.603: E/AndroidRuntime(18726): 	... 11 more
```

**Comment by kentarosu** [comment]
I thought I was the only one. This is my exact error. I've been using 0.6.3.4, but I can only use it locally now, as it seems to have disappeared from the net so Jenkins can't find anymore. :(

**Comment by kentarosu** [comment]
@markchristopherng , I think this might actually be a problem with Calligraphy.

**Comment by kentarosu** [comment]
Sorry for the many, many comments. A temporary(?) workaround is to cast `this`. I noticed my Fragment could still use this library successfully, so I decided to try and catch the one dialog in an Activity to FragmentActivity. Worked.

```
dialog = new MaterialDialog.Builder((FragmentActivity)this)
                .progress(true, 0)
                .title("Logging in...")
                .build();
```

**Comment by afollestad** [comment]
@kentarosu 0.6.3.4 of Material Dialogs? That's very, very old if you're talking about my library.

**Comment by kentarosu** [comment]
Yeah, but updating to the latest doesn't solve my issue.

**Comment by afollestad** [comment]
Well regardless, you shouldn't be using a version that old. 0.7.0 was pretty much a redesign which had lots of contributions from Nova Launcher's dev. Pretty much every update after that has added very important stuff.

**Comment by afollestad** [comment]
However this issue doesn't look fixable to me. 

I think it might be related to Google's AppCompat update (22.1.0) which changes the logic for activities (`ActionBarActivity` -> `AppCompatActivity`).

None of the code in that LogCat is from my library.

**Comment by afollestad** [comment]
Forcing the use of AppCompat 21 may fix the issue, but I wouldn't recommend it.

```groovy
compile('com.android.support:appcompat-v7:21.+@aar') {force=true}
```

**Comment by Unpublished** [comment]
Fixed in new AppCompat 22.1.1.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.2.8

**Comment by jssingh** [comment]
On latest material dialogs (0.7.2.8) and 2.0.2 for calligraphy and still having issues with AppCompat 22.1.1. Whats the fix here? Wouldn't want to give up any library but having the same inflater issue.

Thanks!

**Comment by afollestad** [comment]
Hmm, well sorry there's not much I can do then.

I would still try forcing an older version of AppCompat to be used by putting the line in one of my comments above in your app's build.grade file.

**Comment by jssingh** [comment]
Except it throws an exception in material-dialogs:
Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Dialog.Alert'.

Seems you might be using a v22+ artifact not present in v21. Or am i missing something?

**Comment by afollestad** [comment]
Oh, yeah you're right. I'm using AppCompat Dialog themes now. Well the only other solution would be to tell the dev of the calligraphy library that he needs to update his library; this is ultimately an issue with his  library not being up to date.

**Comment by afollestad** [comment]
His library is using build tools 21.1.2 (instead of 22.0.1) and AppCompat 21.0.3 (instead of 22.1.1).

**Comment by jssingh** [comment]
Seems to make sense. Let me ask you something here - is it possible for your to get 0.7.2.4 (alongside 0.7.2.8) back up on jcenter again? One that uses the older appcompat. This is while Calligraphy dev gets his library on the latest and greatest. Its just a request, and 'no' would be a perfectly fine answer.

**Comment by afollestad** [comment]
Unfortunately I can't, the library had gotten removed from jCenter completely by accident. It recently went back up but I don't keep old versions around.

It would be easy for someone to make a pull request to Calligraphy to update it though.
